apiVersion: v2
name: cosmocloud-deploy
description: Helm chart to deploy backend, frontend, and Redis services as defined in task round for cosmocloud
type: application
version: 1.0.0
appVersion: 1.0.0
